// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqrxpyijxdmscpngnjju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_V5qABGDZB6e8QICR8SbkgQ_jka2x9lC";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // sessionStorage (not localStorage): the session must NOT survive closing the
    // browser — closing all tabs clears it, so the user has to sign in again next time.
    // Reloading the page within the same tab still keeps them signed in. Note this also
    // means the session is per-tab, not shared across tabs like localStorage was.
    // NOTE: this file is marked auto-generated — if it's ever regenerated by Supabase/
    // Lovable codegen, this override will need to be reapplied.
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});